// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sudoku.Data;

#nullable disable

namespace Sudoku.Migrations
{
    [DbContext(typeof(SudokuDbContext))]
    [Migration("20260310200129_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("Sudoku.Entity.GameEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Difficulty")
                        .HasColumnType("TEXT")
                        .HasColumnName("difficulty");

                    b.Property<bool>("Finished")
                        .HasColumnType("INTEGER")
                        .HasColumnName("finished");

                    b.Property<int>("Mistakes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mistakes");

                    b.Property<string>("Time")
                        .HasColumnType("TEXT")
                        .HasColumnName("time");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("Sudoku.Entity.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<Guid>("Password")
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<Guid>("Salt")
                        .HasColumnType("TEXT")
                        .HasColumnName("salt");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("userName");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
